executable = job.sh

arguments = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/SimulateLLP.py \
 --nevents 100 \
 --UseGPUs \
 --SaveAllEvents \
 --mass 130 \
 --eps 5e-6 \
 --bias 1 \
 --LLP-model DarkLeptonicScalar \
 --parentdirectory /data/user/axelpo/LLP-data/No_LLP_natural_rate.$(ClusterId)/ \
 --dirname FullSimulation.$(ClusterId).$(ProcId) \

log = /scratch/axelpo/job.log.$(ClusterId).$(ProcId)
output = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/logs/job.out.$(ClusterId).$(ProcId)
error = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/logs/job.err.$(ClusterId).$(ProcId)
notification = never

+FileSystemDomain = "foo"
transfer_input_files = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/SimulateLLP.py

request_cpus = 5
request_memory = 8GB
request_disk = 2GB
request_gpus = 1

queue 10