executable = job.sh

arguments = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/SimulateLLP.py \
 --nevents $(NEVENTS) \
 --UseGPUs \
 --mass $(MASS) \
 --eps $(EPS) \
 --bias $(BIAS) \
 --LLP-model $(MODEL)

log = /scratch/axelpo/job.log.$(ClusterId)
output = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/logs/job.out.$(ClusterId)
error = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/logs/job.err.$(ClusterId)
notification = never

+FileSystemDomain = "foo"
transfer_input_files = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/SimulateLLP.py

request_cpus = 5
request_memory = 8GB
request_disk = 2GB
request_gpus = 1

queue NEVENTS,MASS,EPS,BIAS,MODEL from llp_config_list.txt