executable = job_darkphoton.sh

arguments = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/SimulateLLP.py \
 --nevents 100 \
 --UseGPUs \
 --no-natural-rate \
 --mass 50 \
 --eps 5e-6 \
 --bias 3e9 \
 --LLP-model DarkPhoton \
 --parentdirectory /data/user/axelpo/LLP-data/DarkPhoton.mass-50.0.eps-5e-06.nevents-10000_230904_fullycontained_condor.$(ClusterId)/ \
 --dirname LLPSimulation.DP.$(ClusterId).$(ProcId) \

log = /scratch/axelpo/job.log.$(ClusterId).$(ProcId)
output = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/logs/job.out.$(ClusterId).$(ProcId)
error = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/logs/job.err.$(ClusterId).$(ProcId)
notification = never

+FileSystemDomain = "foo"
transfer_input_files = /data/user/axelpo/LLP-at-IceCube/dark-leptonic-scalar-simulation/SimulateLLP.py

request_cpus = 5
request_memory = 8GB
request_disk = 2GB
request_gpus = 1

queue 10